### PR TITLE
Adding support for diff and compilation of Solidity with solc.

### PR DESCRIPTION
**Pull request by shoenseiwaso**
@Arachnid we've made some improvements to evmdis that we'd like to share. Awesome piece of work, by the way. We've used evmdis to learn about Solidity. In that sense our changes were fairly high-level and not fundamental to the disassembler, but hopefully you find them useful.

Summary:
* Allow Solidity source code to be passed as input.
* Automatically detect Solidity source code vs. bytecode-as-hex, and compile via solc if required.
* If two sets of input (<stdin>, filename(s) on command line) are provided, diff with coloured output.
* Diff abstract interpreted disassembly by default, but optionally diff Solidity source code (if available) and bytecode-as-hex as well.
* Suppress printing of empty stack frames with no embedded instructions.
* Update README with simple building instructions.

Myself and @william are launching a blockchain startup and doing a survey of different open source blockchain projects to help bring ourselves up to speed. We wrote a blog post about our experience with evmdis here:
http://blog.curvegrid.com/daysofblock/2017/05/11/daysofblock-01-evmdis.html

We understand this might start to take evmdis in a direction you don't want, and we're fine if you'd prefer to exclude these changes altogether or just cherry pick from them. We'll maintain our fork at curvegrid/evmdis-with-diff

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks for the PR!

The bugfix and readme update are very welcome as-is - any chance you could split them out into a separate PR?

I like the idea of doing diffs of both Solidity code and assembly, and of compiling solidity code, but it seems to me that in the Unix pattern of things, these should be a separate command that calls evmdis to do the actual assembly. Would you be open to refactoring it to fit that pattern, instead of making it all part of evmdis itself?

**Comment by shoenseiwaso** [comment]
Thanks for the quick reply and feedback. I can close this PR and open a new one with just the README update and bug fix.

Agree that the Unix pattern to piping things together makes sense. Would you be open to an update to evmdis that adds a second command (could be something like evmdiff/main.go) to wrap this functionality and call out to evmdis and (if required) solc?

I think there's value in this because the Unix pattern works well with a single data stream, but multiplexing two instances of solc => evmdis into diff is possible but pretty clunky.

**Comment by Arachnid** [comment]
Yes, an `evmdiff` command would be _awesome_.

**Comment by shoenseiwaso** [comment]
Ok sounds good. I'll close this PR and open two new ones. Travelling from tomorrow so might take some time.

**Pull request closed without merging**
